lib/github_pr_mentions_web/router.ex
defmodule GithubPrMentionsWeb.Router do
  use GithubPrMentionsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GithubPrMentionsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GithubPrMentionsWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GithubPrMentionsWeb do
    pipe_through :browser

    live "/", PageLive, :index
    get "/auth/github/callback", GithubAuthController, :index
    delete "/logout", GithubAuthController, :delete
  end

  scope "/mentions", GithubPrMentionsWeb do
    pipe_through [:browser, :authenticate_user]

    live "/", MentionsLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", GithubPrMentionsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GithubPrMentionsWeb.Telemetry
    end
  end
end

lib/github_pr_mentions_web/views/layout_view.ex
defmodule GithubPrMentionsWeb.LayoutView do
  use GithubPrMentionsWeb, :view
end

lib/github_pr_mentions_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/github_pr_mentions_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/github_pr_mentions_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Github Pull Request Mentions", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
            <%= if @conn.assigns.current_user do %>
              <li><%= @conn.assigns.current_user.login %></li>
              <li><%= link "Logout", to: Routes.github_auth_path(@conn, :delete), method: "delete" %></li>
            <% end %>
          </ul>
        </nav>
        <%= link to: Routes.page_path(@conn, :index), class: "phx-logo" do %>
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        <% end %>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>